# ~ = arbitrary values
# \ = optional

# spawn: spawn coordinates in your default server world
# ores: <material_name>: [yratio (% of lower y took), gauss factor, gauss offset, [bounds of i, j, k (lode size)], lodes per 100^3 cubes]
# <~campStringID>: [<x>, <y>, <z>, <isFacingNorth?>]
# camps are squared, a face of this square is 2 times camp_size, same for vital_zone

# time in seconds
pvp_time: 60
# delay in seconds
regeneration_delay: 15
# range of teleportation around flags
tp_range: 5.5
# keeps worlds loades
preload_worlds: true

maps:
  spawn:
    world_name: "lobby"
    world_spawn: [0, 10, 0]
  test:
    playable_area: 200
    camps:
      camp_size: 19.5
      vital_size: 8.5
      positions:
        meadow: [-116.5, 71.0, 346.5, "east"]
        coast: [0.5, 80.0, 480.5, "north"]
        lake: [-112.5, 101.0, 480.5, "west"]
    highest_ground: 95
    chamber_height: -17
    lodes_active: false
    lodes:
      ores:
        coal_ore:       [1.0, 5, 1.3, [2.0, 4.5, 1.0, 3.5, 1.0, 1.5], 115]
        iron_ore:       [1.0, 2, 1.2, [1.5, 3.5, 1.0, 2.5, 1.0, 1.5], 240]
        copper_ore:     [0.8, 3, 1.0, [1.0, 2.0, 0.5, 1.5, 0.5, 1.0], 60]
        gold_ore:       [0.6, 2, 0.8, [1.5, 2.5, 1.0, 2.0, 0.5, 1.0], 60]
        redstone_ore:   [0.3, 3, 1.2, [1.0, 2.0, 1.0, 1.5, 0.5, 1.0], 50]
        lapis_ore:      [0.3, 3, 1.2, [1.5, 3.0, 1.0, 2.0, 1.0, 1.5], 50]
        diamond_ore:    [0.3, 6, 0.6, [1.0, 2.0, 0.5, 1.5, 0.5, 1.0], 100]
        emerald_ore:    [0.2, 7, 1.0, [1.0, 1.5, 0.5, 1.0, 0.5, 1.0], 50]
        ancient_debris: [0.1, 1, 1.8, [0.5, 1.0, 0.5, 1.0, 0.5, 1.0], 60]
        

teams:
# <teamName>: "[ChatColor, flagMaterial, DyeColor, red, green and blue value of team Color]"
  Oranges: ["gold", "orange_concrete", "orange", 255, 120, 0]
  Rouges: ["red", "red_concrete", "red", 255, 0, 0]
  Violets: ["light_purple", "purple_concrete", "purple", 160, 0, 255]

# WIP
mobs:
  equipment:
    armor:
      chance: 0.5
      drop_chance: 0.75
    weapon:
      chance: 0.7
      drop_chance: 0.55
    enchantment:
      chance: 0.4
      up_chance: 0.6
      amount: 3
      allowed:
        armor:
        axe:
        sword:
        bow:
  effect:
    allowed:
      absorption: true
      damage_resistence: true
      fire_resistence: true
      health_boost: true
      increase_damage: true
      invisibility: true
      jump: true
      regeneration: true
      slow_falling: true
      speed: true
    chance: 0.4
    up_chance: 0.4
    amount: 3

skills:
  ############### RESSOURCES ###############
  # you melt ores on destruction
  forge: true
  # you make trees fall when their base is broke
  abattage: true
  # spawn with a dog
  dresseur: true
  # do something
  fermier: false
  # don't get hunger
  glouton: true
  # do something
  enchantement: false
  # do something
  alchimie: false
  ###############   CAMPS    ###############
  # do something
  protection: false
  # do something
  construction: false
  # breaking a tnt make the explosion more ... explosive
  demolition: true
  # fireworks break 1 block
  artifice: true
  # no falling damages except in ennemies camps
  roublard: true
  ###############   COMBAT   ###############
  # visible ennemies within 10 blocks appears as glowing for you
  clairvoyance: true
  # you can see the footprints of ennemies but everyone can see your footprints
  pistage: true
  # remove bow and crossbow innaccuracy but arrows deal less damages
  precision: true
# WIP