# ~ = arbitrary values
# \ = optional

# camps are squared, a face of this square is 2 times camp_size, same for vital_zone

maps:
  spawn:
  # spawn coordinates in the lobby world
    worldname: "lobby"
    location: [0.5, 10.0, 0.5]
  generic:
    playable_area: 190
    camps:
      positions:
      # <~campStringID>: [<x>, <y>, <z>, <isFacingNorth?>]
        hill: [-879.5, 70.0, 435.5, true]
        river: [-935.5, 64.0, 312.5, false]
        foreset: [-1027.5, 64.0, 415.5, true]
      settings:
        camp_size: 19.5
        vital_size: 8.5
    chamber_active: true
    chamber:
      max_height: 16
    lodes_active: true
    lodes:
    # highest ground to generate ores (in the majority of cases take the highest stone block)
      highest_ground: 72
      ores:
      # <materialName>: [yratio (% of lower y took), gauss factor, gauss offset, [bounds of i, j, k (lode size)], lodes per 100^3 cubes]
        coal_ore:       [1.0, 5, 1.2, [2.0, 4.5, 1.0, 3.5, 1.0, 1.5], 115]
        iron_ore:       [1.0, 2, 1.1, [1.5, 3.5, 1.0, 2.5, 1.0, 1.5], 160]
        copper_ore:     [0.8, 3, 1.0, [1.0, 2.0, 0.5, 1.5, 0.5, 1.0], 60]
        gold_ore:       [0.6, 2, 0.8, [1.5, 2.5, 1.0, 2.0, 0.5, 1.0], 60]
        redstone_ore:   [0.3, 3, 1.2, [1.0, 2.0, 1.0, 1.5, 0.5, 1.0], 50]
        lapis_ore:      [0.3, 3, 1.2, [1.5, 3.0, 1.0, 2.0, 1.0, 1.5], 50]
        diamond_ore:    [0.3, 6, 0.6, [1.0, 2.0, 0.5, 1.5, 0.5, 1.0], 100]
        emerald_ore:    [0.2, 7, 1.0, [1.0, 1.5, 0.5, 1.0, 0.5, 1.0], 50]
        ancient_debris: [0.1, 1, 1.8, [0.5, 1.0, 0.5, 1.0, 0.5, 1.0], 60]
        

teams:
# <displayName>: "[flagMaterial, DyeColor, Color, ChatColor]"
  Oranges: ["gold", "orange_concrete", "orange", "orange"]
  Rouges: ["red", "red_concrete", "red", "red"]
  Violets: ["light_purple", "purple_concrete", "purple", "purple"]

# WIP
mobs:
  equipment:
    armor:
      chance: 0.5
      drop_chance: 0.75
    weapon:
      chance: 0.7
      drop_chance: 0.55
    enchantment:
      chance: 0.4
      up_chance: 0.6
      amount: 3
      allowed:
        armor:
        axe:
        sword:
        bow:
  effect:
    allowed:
      absorption: true
      damage_resistence: true
      fire_resistence: true
      health_boost: true
      increase_damage: true
      invisibility: true
      jump: true
      regeneration: true
      slow_falling: true
      speed: true
    chance: 0.4
    up_chance: 0.4
    amount: 3

skills:
  ############### RESSOURCES ###############
  # you melt ores on destruction
  forge: true
  # you make trees fall when their base is broke
  abattage: true
  # spawn with a dog
  dresseur: true
  # do something
  fermier: false
  # don't get hunger
  glouton: true
  # do something
  enchantement: false
  # do something
  alchimie: false
  ###############   CAMPS    ###############
  # do something
  protection: false
  # do something
  construction: false
  # breaking a tnt make the explosion more ... explosive
  demolition: true
  # no falling damages except in ennemies camps
  roublard: true
  ###############   COMBAT   ###############
  # visible ennemies within 10 blocks appears as glowing for you
  clairvoyance: true
  # you can see the footprints of ennemies but everyone can see your footprints
  pistage: true
  # remove bow and crossbow innaccuracy but arrows deal less damages
  precision: true
# WIP

# time in seconds
pvp_time: 600
# delay in seconds
regeneration_delay: 15
# range of teleportation around flags
tp_range: 5.5