# ~ = arbitrary values
# \ = optional

# count: [<coal>, <iron>, <copper>, <gold>, <redstone>, <lapis>, <diamond>, <emerald>, <debris>]
# <~campName>: [<x>, <y>, <z>, <isFacingNorth?>]
# real camp size = 2*camp_size
current_map: "generic"

maps:
  generic:
    lodes:
      ground_level: 55
      count: [100, 80, 60, 10, 40, 40, 30, 10, 20]
    camps:
      positions:
        hill: [-879.5, 70.0, 435.5, true]
        river: [-935.5, 64.0, 312.5, false]
        foreset: [-1027.5, 64.0, 415.5, true]
      settings:
        camp_size: 16.5
        ratio: 0.51
        

# <teamConcreteColor>: "<\chatColor char><displayName>"
teams:
  orange: "6Oranges"
  red: "cRouges"
  purple: "dViolets"

# time in seconds
pvp_time: 900
# delay in seconds
regeneration_delay: 15
# range of teleportation around flags
tp_range: 5.5