name: LostSettlers
version: '3.0'
author: loferga
main: fr.loferga.lost_settlers.Main
api-version: '1.17'
api: '1.17'
depend: [ProtocolLib]

commands:
  lobby:
    description: LostSettlers command to tp the sender to the lobby world
  all:
    description: LostSettlers command to send a message with all the players in a world
  lsteam:
    description: LostSettlers command to change a player\'s team, non-operators can only change their team
  start:
    description: LostSettlers command to start a new game in a specified world (set the worldspawn to the center of the camps)
    permission: op
  end:
    description: LostSettlers command to stop a running game in the player\'s world
    permission: op
  warp:
    description: LostSettlers command to load a world and tp to it\'s WorldSpawn
    permission: op
  close:
    description: LostSettlers command to tp everyone in a specified world to the lobby world and either store or restore the world
    permission: op
  clearores:
    description: LostSettlers command to clear all ores in the player\'s world playable area
    permission: op